### ISSUE TITLE
感谢大佬！！不过现在好像用不了了

### ISSUE THREAD

**Issue by Ungezieferrr** [YunzheZJU/ComicWalkerWalker#2]
一直显示网络连接不畅…

**Comment by YunzheZJU** [comment]
感谢反馈！
这3年间一直没有维护，看起来它已经坏了。
我这几天试着修一下吧。
如果图片的加密和编码方法已经更改，那就相当于重写了...
由于我已经不写Python了，可能会用Ruby/JavaScript重写。

**Comment by Ungezieferrr** [comment]
非常感谢，真的辛苦了！
我是汉化组的一员，最近我们想要接手一部在cw发布的漫画，但是一直找不到扒下图源的方法，甚至开始考虑使用截图这个最终笨办法了
我不是很懂编程，不过如果在语言改变后，仍然能够通过路径打开exe使用的话，那就太好啦。
再次致以诚挚的谢意！！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YunzheZJU/ComicWalkerWalker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 中午1:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YunzheZJU/ComicWalkerWalker] 感谢大佬！！不过现在好像用不了了 (#2)





 
感谢反馈！
 这3年间一直没有维护，看起来它已经坏了。
 我这几天试着修一下吧。
 如果图片的加密和编码方法已经更改，那就相当于重写了...
 由于我已经不写Python了，可能会用Ruby/JavaScript重写。

**Comment by Ungezieferrr** [comment]
不好意思，再打扰一下啦！
我发现使用vpn后就能够成功扒图了！！
非常抱歉这个程序真的非常好用，已经成功理好图源啦！
再次感谢大佬的辛勤付出和耐心回复~





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YunzheZJU/ComicWalkerWalker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 中午1:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YunzheZJU/ComicWalkerWalker] 感谢大佬！！不过现在好像用不了了 (#2)





 
感谢反馈！
 这3年间一直没有维护，看起来它已经坏了。
 我这几天试着修一下吧。
 如果图片的加密和编码方法已经更改，那就相当于重写了...
 由于我已经不写Python了，可能会用Ruby/JavaScript重写。

**Comment by YunzheZJU** [comment]
我自己测了下，找了很多漫画都不成功（包括蜘蛛子），显示“未找到章节列表”，检查了下是网页的格式有更新，于是更新了一下代码，现在应该能正常工作了。
但我很奇怪你是怎么成功的（即使解决了网络问题）...可能你的目标还处在旧版网页，因此本工具仍然可以工作。

如果方便的话可以[下载](https://github.com/YunzheZJU/ComicWalkerWalker/archive/refs/heads/master.zip)一下最新版本的工具，测试一下你的目标漫画能否正常下载吗？

**Comment by Ungezieferrr** [comment]
不好意思，昨天忙得没时间回复orz
尝试了下新版的，完全成功啦！
我下载的漫画所在的网址是这个：大神官様は婚活中 無料漫画詳細 - 無料コミック ComicWalker (comic-walker.com)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YunzheZJU/ComicWalkerWalker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月5日(星期六) 凌晨0:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YunzheZJU/ComicWalkerWalker] 感谢大佬！！不过现在好像用不了了 (#2)





 
我自己测了下，找了很多漫画都不成功（包括蜘蛛子），显示“未找到章节列表”，检查了下是网页的格式有更新，于是更新了一下代码，现在应该能正常工作了。
 但我很奇怪你是怎么成功的（即使解决了网络问题）...可能你的目标还处在旧版网页，因此本工具仍然可以工作。
 
如果方便的话可以下载一下最新版本的工具，测试一下你的目标漫画能否正常下载吗？

**Comment by YunzheZJU** [comment]
好的，多谢帮忙测试！
若将来遇到其他问题可以同样开Issue提问~
